"""empty message

Revision ID: a68e2a916d23
Revises: 
Create Date: 2018-11-26 21:33:52.609494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a68e2a916d23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spelling_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duedate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('classname', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_classname'), 'user', ['classname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('spellingtest_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spellingtest_id'], [u'spelling_test.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_result_score'), 'test_result', ['score'], unique=False)
    op.create_index(op.f('ix_test_result_timestamp'), 'test_result', ['timestamp'], unique=False)
    op.create_table('test_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=128), nullable=True),
    sa.Column('samplesentence', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], [u'spelling_test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_words_word'), 'test_words', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_words_word'), table_name='test_words')
    op.drop_table('test_words')
    op.drop_index(op.f('ix_test_result_timestamp'), table_name='test_result')
    op.drop_index(op.f('ix_test_result_score'), table_name='test_result')
    op.drop_table('test_result')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_classname'), table_name='user')
    op.drop_table('user')
    op.drop_table('spelling_test')
    # ### end Alembic commands ###
